// <auto-generated />
using System;
using APBD_KOL1_Poprawa.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_KOL1_Poprawa.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240622161154_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.Access", b =>
                {
                    b.Property<int>("IdAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccess"));

                    b.Property<int>("IdProject")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdAccess");

                    b.HasIndex("IdProject");

                    b.HasIndex("IdUser");

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.Project", b =>
                {
                    b.Property<int>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProject"));

                    b.Property<int>("IdDefaultAssignee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProject");

                    b.HasIndex("IdDefaultAssignee");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.Task", b =>
                {
                    b.Property<int>("IdTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTask"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAssignee")
                        .HasColumnType("int");

                    b.Property<int>("IdProject")
                        .HasColumnType("int");

                    b.Property<int>("IdReporter")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTask");

                    b.HasIndex("IdAssignee");

                    b.HasIndex("IdProject");

                    b.HasIndex("IdReporter");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.Access", b =>
                {
                    b.HasOne("APBD_KOL1_Poprawa.Models.Project", "projectNavigation")
                        .WithMany("accessNavigation")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_KOL1_Poprawa.Models.User", "userNavigation")
                        .WithMany("accessNavigation")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("projectNavigation");

                    b.Navigation("userNavigation");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.Project", b =>
                {
                    b.HasOne("APBD_KOL1_Poprawa.Models.User", "defaultAssigneeNavigation")
                        .WithMany("projectNavigation")
                        .HasForeignKey("IdDefaultAssignee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("defaultAssigneeNavigation");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.Task", b =>
                {
                    b.HasOne("APBD_KOL1_Poprawa.Models.User", "assigneeNavigation")
                        .WithMany("taskAssigneNavigation")
                        .HasForeignKey("IdAssignee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_KOL1_Poprawa.Models.Project", "projectNavigation")
                        .WithMany("TaskNavigation")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_KOL1_Poprawa.Models.User", "reporterNavigation")
                        .WithMany("taskReporterNavigation")
                        .HasForeignKey("IdReporter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assigneeNavigation");

                    b.Navigation("projectNavigation");

                    b.Navigation("reporterNavigation");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.Project", b =>
                {
                    b.Navigation("TaskNavigation");

                    b.Navigation("accessNavigation");
                });

            modelBuilder.Entity("APBD_KOL1_Poprawa.Models.User", b =>
                {
                    b.Navigation("accessNavigation");

                    b.Navigation("projectNavigation");

                    b.Navigation("taskAssigneNavigation");

                    b.Navigation("taskReporterNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
